fixtures:
  # use the forge modules so we can easily pin to a specific version
#  forge_modules:
#    stdlib: "puppetlabs/stdlib"
repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    vscrepo: "git://github.com/puppetlabs/puppetlabs-vcsrepo.git"
    python: "git://github.com/stankevich/puppet-python.git"
    uwsgi: "git://github.com/Engage/puppet-uwsgi.git"
  symlinks:
    helios: "#{source_dir}"
    #stdlib: "/home/abaranov/work/lf/LFInfra/environments/production/modules/stdlib"
    #vcsrepo: "/home/abaranov/work/lf/LFInfra/environments/production/modules/vcsrepo"
    #python: "/home/abaranov/work/lf/LFInfra/environments/production/modules/python"
    #uwsgi: "/home/abaranov/work/lf/LFInfra/environments/production/modules/uwsgi"
